/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.android.gts.locationcontext;

import android.hardware.location.ContextHubManager;
import android.hardware.location.ContextHubMessage;
import android.hardware.location.NanoApp;
import android.util.Log;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

/**
 * A base class for many kind of Nanoapp tests.
 *
 * In the vast majority of cases, you want to use
 * GtsContextHubGeneralNanoAppTestBase instead of directly using this class.
 * That class is heavily documented.  Please see it.  Notably, when using
 * GtsContextHubGeneralNanoAppTestBase, you can completely ignore this class,
 * as the only abstract methods of note are (re)declared in
 * GtsContextHubGeneralNanoAppTestBase.
 *
 * This class is more lightly documented, as it's considered more "expert"
 * level.
 */
public abstract class GtsContextHubNanoAppTestBase {
    private static final String TAG = "GtsContextHubNanoAppTestBase";

    // Amount of time to wait for system to reboot after a failure
    // (enough time for system to come up before starting a new test).
    private static final long SYSTEM_REBOOT_WAIT_SECONDS = 10;

    private ContextHubManager.Callback mCallback = new ContextHubManager.Callback() {
        public void onMessageReceipt(int hubHandle, int nanoAppHandle,
                                     ContextHubMessage message) {
            try {
                messageHandler(hubHandle, nanoAppHandle, message);
            } catch (AssertionError e) {
                // We assume this error was generated by JUnit.  JUnit doesn't
                // support assertions outside of the main test thread.  This
                // callback is always invoked from a different thread, and
                // thus cannot throw this exception.
                mAssertion = e;
                mTestDone.countDown();
            }
        }
    };

    private static final String NANO_APP_PUBLISHER = "Google";

    private GtsContextHubManagerWrapper mContextHubManager = null;

    // We need to stall the main test thread, so it can wait for our messages
    // to/from our nanoapp to play out and perform the test.  We wait on this
    // latch for that, and let the "pass"ing path trigger this.
    private final CountDownLatch mTestDone = new CountDownLatch(1);
    private AssertionError mAssertion = null;

    // TODO(b/31912117): We have a bug where we incorrectly report the last
    //     error in a test, instead of the first one.  So we track our
    //     stages (@Before, @Test, and @After) and only report an error from
    //     @After if our stageSuccessCount was incremented in both @Before and
    //     @Test.
    private int mStageSuccessCount = 0;

    /**
     * General test set up
     */
    @Before
    public void startTest() {
        mStageSuccessCount = 0;
        mContextHubManager = createContextHubManager();
        loadAndStart();
        // We'll only get here if we didn't throw an exception above.
        mStageSuccessCount++;
    }

    /**
     * General JUnit4 test
     */
    @Test
    public void runTest() throws InterruptedException {
        // All the test logic takes place in callbacks invoked in other threads.
        // Our job here is to "wait" until one of those callbacks sets
        // our success flag.  If it takes too long for success to be
        // signaled, we'll fail.
        boolean inTime = mTestDone.await(getTestTimeoutSeconds(), TimeUnit.SECONDS);
        if (!inTime) {
            Assert.fail("Test took longer than " + getTestTimeoutSeconds() + " seconds.");
        }
        if (mAssertion != null) {
            // Our test failed due to an assertion.  We'll throw it here.
            // Test failures may cause the system to reboot, so wait
            // until the system restarts.
            try {
                TimeUnit.SECONDS.sleep(SYSTEM_REBOOT_WAIT_SECONDS);
            } catch (InterruptedException e) {
                Log.e(TAG, "Interrupted during sleep after a test failure.");
            }
            throw mAssertion;
        }
        // Returning from this function indicates a passing test.
        mStageSuccessCount++;
    }

    /**
     * General test tear down
     */
    @After
    public void endTest() {
        if (mContextHubManager == null) {
            // Nothing to clean up.
            return;
        }
        try {
            // It is critical that we call close() on our ContextHubManager
            // no matter what.  Failure to call this will cause all
            // subsequent tests to fail (due to ContextHubManager not
            // allowing more than one callback to be registered).
            // However, we do need this 'open' for unloading our
            // nanoapps.  So we structure this code to make sure we
            // call close(), but also make sure to pass on any
            // test failure.
            try {
                unload();
            } finally {
                mContextHubManager.close();
            }
        } catch (AssertionError e) {
            // TODO(b/31912117): We want to remove all this eventually.  But
            //     for now, 'e' will always be reported by GTS as the reason
            //     our test failed, even if this test initially failed due to
            //     an earlier error.  This workaround logic will have us only
            //     tell GTS about this failure if it's our first one.
            if (mStageSuccessCount == 2) {
                // We succeeded @Before and @Test.  Pass this failure on for
                // GTS to report it.
                throw e;
            } else {
                // Not our first error.  We'll log it, but not tell GTS
                // about it, so it can report our earlier error instead.
                Log.e(TAG, "Further error caught in @After: " + e.toString());
            }
        }
    }

    /**
     * START HELPER METHODS DESIGNED FOR USE BY CHILDREN TEST CLASSES.
     */

    /**
     * @return The private 'callback' which is needed for instantiating
     *     a GtsContextHubManagerWrapper.
     */
    protected ContextHubManager.Callback getCallback() {
        return mCallback;
    }

    /**
     * @return The context hub manager wrapper.
     */
    protected GtsContextHubManagerWrapper getContextHubManager() {
        return mContextHubManager;
    }

    /**
     * Loads the given nanoapp.
     *
     * @param appName  The text name of the app, used in logging errors.
     * @param nanoAppFilename  The name of the .napp file to load.
     *
     * @return The ContextHubManager's "handle" to the nanoApp.  If this
     *     nanoapp cannot be loaded, this method triggers a test failure.
     */
    protected int loadNanoApp(String appName, String nanoAppFilename) {
        NanoApp app = GtsContextHubNanoAppCreator.create(mContextHubManager.getContextHubInfo(),
                nanoAppFilename);
        // TODO(b/30808791): Confirm that app.getId()'s five most significant
        //     bytes are GtsContextHubManagerWrapper.GTS_VENDOR_ID.
        app.setName(appName);
        app.setPublisher(NANO_APP_PUBLISHER);

        int nanoAppHandle = mContextHubManager.loadNanoApp(app);
        Assert.assertTrue("Unable to load nanoapp " + appName,
                          nanoAppHandle != -1);

        return nanoAppHandle;
    }

    /**
     * Unloads the given nanoapp.
     *
     * @param appName  The text name of the app, used in logging errors.
     * @param nanoAppHandle  The "handle" given by loadNanoApp.
     *
     * @return No value.  If this nanoapp cannot be unloaded, this method
     *     triggers a test failure.
     */
    protected void unloadNanoApp(String appName, int nanoAppHandle) {
        int result = mContextHubManager.unloadNanoApp(nanoAppHandle);
        Assert.assertEquals("Failed to unload nanoapp " + appName,
                            0, result);
    }

    /**
     * Complete a test as passing.
     *
     * @return  This method does return, but no further work should be done
     *     by the caller.
     */
    protected void pass() {
        mTestDone.countDown();
    }


    /**
     * START PROTECTED METHODS YOU MIGHT WANT TO OVERRIDE.
     */

    /**
     * Useful if a test wants to use a custom GtsContextHubManagerWrapper.
     *
     * @return A new GtsContextHubManagerWrapper instance.
     */
    protected GtsContextHubManagerWrapper createContextHubManager() {
        return new GtsContextHubManagerWrapper(mCallback);
    }


    /**
     * START ABSTRACT METHODS REQUIRED TO BE IMPLEMENTED BY CHILDREN CLASSES.
     */

    /**
     * Invoked during the @Before portion of a test, after the
     * ContextHubManager is created.  As the name suggests, it's expected
     * that nanoapps will be loaded and the tests begun in this method.
     */
    protected abstract void loadAndStart();

    /**
     * Invoked during the @After portion of a test, before the
     * ContextHubManager is closed.  As the name suggests, it's expected
     * that nanoapps will be unloaded in this method.
     */
    protected abstract void unload();

    /**
     * Handler for messages from the Context Hub which weren't consumed
     * by the GtsContextHubManagerWrapper.
     *
     * @param hubHandle  Handle of the originating Context Hub.
     * @param nanoAppHandle  Handle of the originating NanoApp.
     * @param message  The message sent by 'nanoAppHandle' on 'hubHandle'.
     */
    protected abstract void messageHandler(int hubHandle, int nanoAppHandle,
                                           ContextHubMessage message);

    /**
     * Get the number of seconds after which a test should be considered failed.
     *
     * This is the amount of time after the nanoapps have loaded, and before
     * they have been unloaded.  Thus, this just covers the time spent running
     * the actual test.
     *
     * This is intended to keep tests from running "forever".  This is not
     * intended to be used to perform specific timing checks for a test (note
     * that our precision here is just in seconds).  Tests which require/expect
     * precise timings should internally check for that, using this mechanism
     * only as a fallback for things falling apart overall.
     *
     * Error on the side of making this value too large.  If this value is
     * too small, we risk failures due to flakiness (a test that would have
     * passed if it had been given longer).  If this value is too large, we
     * end up waiting longer in a failure case where expected communications
     * which didn't come across.  We'd much rather wait a little longer to
     * report an overall failure than risk a flaky test.
     *
     * @return The number of seconds after which to give up on a test as
     *     not responding properly.
     */
    protected abstract long getTestTimeoutSeconds();
}
